In [1]:
import numpy as np
import pandas as pd

# Series

In [2]:
data = [101, 102, 104]

series = pd.Series(data)
print(series)

# Changing indexes means giving Labels:
series = pd.Series(data, index= ["a", "b", "c"])
print(series)

0    101
1    102
2    104
dtype: int64
a    101
b    102
c    104
dtype: int64

In [3]:
calories = {
    "day1" : 1700,
    "day2" : 1900,
    "day3" : 2200,
    "day4" : 2700
}

series = pd.Series(calories)
print(series)

day1    1700
day2    1900
day3    2200
day4    2700
dtype: int64

# DataFrame
 3 types:
- ditionary
- lists
- numpy Arrays

In [4]:
# Creating using a Ditionary :

data = {
    "Name" : ["Raza", "Hamza", "Moiz"],
    "Age" : [20, 18, 22]
}

df = pd.DataFrame(data, index=[1, 2, 3])
print(df)

# Add a new Column --------
print("\nThe new column is added..")
df["JOB"] = ["AI", "PUBG", "SE"]

# Add new row--------
new_row = pd.DataFrame([{"Name" : "Bilal", "Age" : 21, "JOB" : "Manager"}],     #can add more rows need practice
                        index = [4])

df = pd.concat([df , new_row])          #concat to join or append

print(df , "\n")
print(df.index) # to know what are the indexes
print(df.columns) # to know the names of the columns

    Name  Age
1   Raza   20
2  Hamza   18
3   Moiz   22

The new column is added..
    Name  Age      JOB
1   Raza   20       AI
2  Hamza   18     PUBG
3   Moiz   22       SE
4  Bilal   21  Manager

Index([1, 2, 3, 4], dtype='int64')
Index(['Name', 'Age', 'JOB'], dtype='object')

In [5]:
# creating Dataframes by using "Lists"
# firstly [] this is a row then , col define the heading of the col
df = pd.DataFrame([["Bilal" , 22] , ["Moiz" , 24] , ["Hamza" , 19]] , columns= ["Name" , "Age"]) 
df

    Name  Age
0  Bilal   22
1   Moiz   24
2  Hamza   19

In [6]:
# Creating using Numpy Arrays:
np_arr = np.array([[1,2,3], [4,5,6]])
df = pd.DataFrame(np_arr , columns= ["A" , "B" , "C"])
df

   A  B  C
0  1  2  3
1  4  5  6

## CSV and JSON read:

In [7]:
# read from csv
# df = pd.read_csv("employee_data.csv")
# df
# read from json file
df = pd.read_json("employee_data.json")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

#### Dataframe Methods

In [8]:
df.head()   # first five rows
df.tail(3)   # last five values
df.sample(4)  # random rows
df.info()  # info of the whole data means summary

df.shape   # a tuple of ( rows , col )

df.describe()  # on all the numerical columns there--- mean, max, min

df.nunique()  # to know the data uniquely that how many dep are there

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

#### AQI Data set:

In [9]:
df  = pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

### Indexing & selecting Data:

In [10]:
# selecting by columns
df["country"]
df[["country" , "aqi" , "city"]]

# selecting by rows:
# using loc & iloc
df.loc[0]  # row 1 data
df.loc[0:3] # start idx : end idx (inclusive)
df.iloc[0]  # row 1 data
df.iloc[0:3]  # start idx : end idx (exclusive)

# cells - Rows + Columns access   ( row  , col)
df.loc[0:9 , ["country" , "city" , "aqi"]]  # if we use iloc here we need to use numeric values only for col as well

# for single scalar value:
df.at[ 0 , "city"]
df.iat[ 0 , 1]

'US'

#### Filtering:

In [11]:
df[ df["aqi"] > 100]
df[ (df["aqi"] > 100) & (df["temperature"] > 30)] [["city" , "country"]]

# Query:
df.query("aqi > 100 & temperature > 30") [["city" , "country"]]
#also refrence can be used:
val = 100
aqi_data = df.query("aqi > @val & temperature > 30") [["city" , "country"]].copy()
aqi_data

           city country
6      New York      US
7      New York      US
14     New York      US
17     New York      US
25     New York      US
...         ...     ...
17947    Zurich      CH
17950    Zurich      CH
17975    Zurich      CH
17976    Zurich      CH
17991    Zurich      CH

[2384 rows x 2 columns]

## Cleaning Data:

### Missing Values:

In [12]:
df = pd.read_csv("raw_data.csv")

In [13]:
 # returns True where the null value is
df.isnull()
df.isna()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [14]:
# chaining --- that how many missing values are in the data
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [15]:
# drops all the null values from the data sets
df.dropna()  # drop rows
df.dropna(axis=1) # drop columns

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [16]:
# fill the null values 
df.fillna(0)
df["age"].fillna(100)

0      29.0
1      29.0
2     100.0
3     100.0
4      34.0
5      27.0
6      45.0
7      38.0
8      29.0
9     100.0
10     31.0
Name: age, dtype: float64

In [17]:
# for forward fill & backward fill
df.ffill()
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [18]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

### Duplicate Value

In [19]:
# check duplicate
df.duplicated()
df["country"].duplicated()
df2 = df.copy()
df2.drop_duplicates(inplace = True)
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [20]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

### Datatypes and Date-time

In [21]:
# know the data type od the table
df.dtypes

# now chnage the type: Firstly fill all the null values...
df2 = df.copy()
df2 = df2.fillna(0)

df2 = df2["age"].astype("int64")
df2.dtypes

# date time function 
date_str = pd.Series(pd.to_datetime("2026-11-09"))
date_str.dtypes

dtype('<M8[ns]')

### Handle Strings

In [22]:
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()

# seperate the data by space 
df["name"].str.split(" ")  

df["country"].str.contains("US")
df["country"].str.contains("india" , case = False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

# Data Transformation (Feature Learning).

In [50]:
df2 = df.copy()

# apply function:
df2["tax"] = df2["income"].apply(lambda x: "20%" if x >= 50000 else "10%")
df2

# map func:
gender_map = {"Male" : "M", "Female" : "F" , "Unknown" : "U"}
df2["gender"] = df2["gender"].map(gender_map)
df2

# assign function:
new_income = df2["income"] * 1.1
df2.assign(new_income = new_income)

# Replace (old , new) func:
df2["country"] = df2["country"].replace("USA" , "US")
df2

# Rename func:
df2.rename(columns = {"income" : "Salary"})
df2.rename(index = {4 : "Fourth"})

# Sorting Values:
# sort_value() func:
sorted_df = df2.sort_values(["income", "tax"])

# sort_index func:
df2.sort_index()  # all thing are reset to orginal

# reset_index func:
df2.reset_index() # new index column will be created to reserve the org index
df2.reset_index(drop = True) # here no reservation of the old indexes 

# rank function:
sorted_df["Rankings"] = sorted_df["income"].rank(ascending=False ,method= "dense")
sorted_df

    id          name   age country gender   income  tax  Rankings
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%       8.0
3    3          Alex   NaN      US      U  47000.0  10%       7.0
5    5        Li Wei  27.0   China      M  51000.0  20%       6.0
0    1      John Doe  29.0      US      M  55000.0  20%       5.0
1    1      John Doe  29.0      US      M  55000.0  20%       5.0
10  10   Emily Davis  31.0      US    NaN  58000.0  20%       4.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%       3.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%       3.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%       2.0
6    6           NaN  45.0   India      F  73000.0  20%       1.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%       NaN

# QUESTION : id wale columns ko end mein le jao ----> ab isme condition lagygi k phle sare columns aye phir end mein id column ko add krna hota ha

In [55]:
df3 = df.copy()

new_col_order = [col for col in df3.columns if col != "id"] + ["id"]

print(new_col_order)
df3[new_col_order]

['name', 'age', 'country', 'gender', 'income', 'id']

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [56]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

# Write The Data Into CSV FILE:

In [61]:
df2 = df.copy()

df2 = df2.drop_duplicates()
df2 = df2.fillna(0)
df2 = df2.sort_values("income")
df2 = df2.reset_index(drop = True)

df2

df2.to_csv("sorted_data_by_me.csv")

# Gouped By & Aggregiate Functions:

In [81]:
df2 = df.copy()

# for group by :
df2.groupby("country")["income"].mean()  # like this max and min and  sum 

# for using multiple functions of mean and sum use aggregiate (agg):
df2.groupby("country")["income"].agg(["mean" , "max" , "min"])
df2.groupby("country")["income"].agg( avg_income = "mean" , max_income =  "max" , min_income =  "min")

# now for group two different thing with two different funcs:
df2.groupby("country").agg({
    "income" : "max",
    "age" : "mean"
})
# name labels:
df2.groupby("country").agg(
    max_income = ("income" , "max"),
    avg_age = ("age" , "mean")
)

         max_income  avg_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         62000.0     29.5

# MELT & PIVOT

In [85]:
df3 = pd.DataFrame({
    "country": ["USA", "USA", "UK", "Canada", "UK"],
    "year": [2022, 2023, 2022, 2023, 2023],
    "sales": [1200, 1500, 900, 1100, 1300],
    "profit": [250, 320, 180, 220, 270]
})
df3

  country  year  sales  profit
0     USA  2022   1200     250
1     USA  2023   1500     320
2      UK  2022    900     180
3  Canada  2023   1100     220
4      UK  2023   1300     270

In [97]:
melted_data = df3.melt(
    id_vars= ["country" , "year"],
    value_vars= ["sales", "profit"],
    var_name= "matrics",
    value_name= "value"
)
melted_data

original = melted_data.pivot(
    index=["country" , "year"],
    columns="matrics",
    values="value"
)
original

matrics       profit  sales
country year
Canada  2023     220   1100
UK      2022     180    900
        2023     270   1300
USA     2022     250   1200
        2023     320   1500

# Merge and Join

In [102]:
employees = pd.DataFrame({
    'emp_id': [1, 2, 3, 4, 5],
    'name': ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal'],
    'department': ['IT', 'HR', 'IT', 'Finance', 'Marketing']
})

salaries = pd.DataFrame({
    'emp_id': [1, 2, 3, 6],
    'salary': [70000, 65000, 80000, 90000],
    'bonus': [5000, 4000, 6000, 7000]
})

# joins:
pd.merge(employees , salaries , on="emp_id" , how="inner")
pd.merge(employees , salaries , on="emp_id" , how="left")
pd.merge(employees , salaries , on="emp_id" , how="right")
pd.merge(employees , salaries , on="emp_id" , how="outer")

   emp_id    name department   salary   bonus
0       1     Ali         IT  70000.0  5000.0
1       2    Sara         HR  65000.0  4000.0
2       3   Ahmed         IT  80000.0  6000.0
3       4  Ayesha    Finance      NaN     NaN
4       5   Bilal  Marketing      NaN     NaN
5       6     NaN        NaN  90000.0  7000.0

# Concatenation

In [108]:
sales_q1 = pd.DataFrame({
    "product": ["Laptop", "Mouse", "Keyboard"],
    "sales": [120, 300, 150]
})

sales_q2 = pd.DataFrame({
    "product": ["Monitor", "Printer", "Speaker"],
    "sales": [80, 60, 140]
})

pd.concat([sales_q1 , sales_q2] , ignore_index=True)   
pd.concat([sales_q1 , sales_q2] , axis=1)

    product  sales  product  sales
0    Laptop    120  Monitor     80
1     Mouse    300  Printer     60
2  Keyboard    150  Speaker    140

In [104]:
sales_q1

    product  sales
0    Laptop    120
1     Mouse    300
2  Keyboard    150

In [105]:
sales_q2

   product  sales
0  Monitor     80
1  Printer     60
2  Speaker    140